import { expect, test } from '@playwright/test'
import { focusedDiscoveryTitleIsReadable } from './helpers/discovery-focus'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('idle-slayer-ascension-map.analytics.v1', 'disabled'))
  await page.route('https://analytics.garrod.house/**', (route) => route.abort())
})

test('arrow selection opens a non-first result through native button focus', async ({ page }, info) => {
  await page.goto('./')
  const input = page.getByRole('searchbox')
  await input.fill('Soul')
  const region = page.getByRole('region', { name: 'Visible upgrade results', exact: true })
  const rows = region.locator('.search-result')
  const count = await rows.count()
  expect(count).toBeGreaterThan(2)
  const chosen = rows.nth(1), id = await chosen.getAttribute('data-upgrade-id'), title = await chosen.locator('.discovery-title').innerText()
  await expect(page.getByRole('button', { name: 'Toggle search results', exact: true })).toHaveAttribute('aria-expanded', 'true')
  await expect(input).toHaveAttribute('aria-controls', (await region.getAttribute('id'))!)
  const status = page.getByRole('status').filter({ hasText: 'Search results open.' })
  await expect(status).toHaveText(`Search results open. ${count} visible results.`)
  await input.press('ArrowDown')
  await expect(rows.nth(0)).toBeFocused()
  await focusedDiscoveryTitleIsReadable(page)
  await page.keyboard.press('End')
  await expect(rows.last()).toBeFocused()
  await focusedDiscoveryTitleIsReadable(page)
  await page.keyboard.press('Home')
  await expect(rows.nth(0)).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(chosen).toBeFocused()
  await expect(chosen).toHaveAttribute('aria-current', 'true')
  await expect(region.locator('[aria-current="true"]')).toHaveCount(1)
  expect(await chosen.getAttribute('aria-describedby')).toBeTruthy()
  const toggleBox = await page.getByRole('button', { name: 'Toggle search results', exact: true }).boundingBox()
  expect(toggleBox!.width).toBeGreaterThanOrEqual(44); expect(toggleBox!.height).toBeGreaterThanOrEqual(44)
  await page.screenshot({ path: info.outputPath('keyboard-candidate.png') })
  await page.keyboard.press('Enter')
  await expect(region).toHaveCount(0)
  await expect(page.locator('.details h2')).toHaveText(title)
  await expect(page.locator('.react-flow__node.selected')).toHaveAttribute('data-id', id!)
  expect(await page.evaluate(() => localStorage.getItem('idle-slayer-ascension-map.profile.v1'))).toBeNull()
})

test('text editing, native Tab and Space remain available alongside arrow selection', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox')
  await input.fill('Soul')
  await input.press('Home')
  await expect(input).toBeFocused()
  expect(await input.evaluate((element) => (element as HTMLInputElement).selectionStart)).toBe(0)
  await input.press('End')
  expect(await input.evaluate((element) => (element as HTMLInputElement).selectionStart)).toBe(4)
  await input.press('ArrowLeft')
  await expect(input).toBeFocused()
  expect(await input.evaluate((element) => (element as HTMLInputElement).selectionStart)).toBe(3)
  await input.press('Tab')
  await expect(page.getByRole('button', { name: 'Close search results', exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('combobox', { name: 'Progress state', exact: true })).toBeFocused()
  const rows = page.locator('.search-result'), secondTitle = await rows.nth(1).locator('.discovery-title').innerText()
  await page.keyboard.press('Tab'); await expect(rows.nth(0)).toBeFocused()
  await page.keyboard.press('Tab'); await expect(rows.nth(1)).toBeFocused()
  await focusedDiscoveryTitleIsReadable(page)
  await page.keyboard.press('Space')
  await expect(page.locator('.details h2')).toHaveText(secondTitle)
})

test('Escape and disclosure expose closed state, then arrows reopen candidates', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox'), toggle = page.getByRole('button', { name: 'Toggle search results', exact: true })
  await input.fill('Soul'); await input.press('ArrowDown')
  await page.keyboard.press('Escape')
  await expect(input).toBeFocused()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('status').filter({ hasText: 'Search results closed.' })).toBeVisible()
  await input.press('ArrowUp')
  await expect(page.locator('.search-result').last()).toBeFocused()
  await focusedDiscoveryTitleIsReadable(page)
  await page.keyboard.press('Escape')
  await input.press('ArrowDown')
  await expect(page.locator('.search-result').first()).toBeFocused()
  await toggle.click()
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('region', { name: 'Visible upgrade results', exact: true })).toHaveCount(0)
})

test('filter and query announce current visible counts and clear previous candidates', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox')
  await input.fill('Soul'); await input.press('ArrowDown')
  await page.getByRole('combobox', { name: 'Progress state', exact: true }).selectOption('pending')
  await expect(page.locator('.search-result')).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: 'Search results open.' })).toHaveText('Search results open. 0 visible results; no matching visible upgrades.')
  await input.fill('PRIVATE UNMATCHED FIXTURE')
  await input.press('Enter')
  await expect(page.locator('.search-result')).toHaveCount(0)
  await expect(page.getByRole('status').filter({ hasText: 'Search results open.' })).not.toContainText('PRIVATE UNMATCHED FIXTURE')
  await expect(page.getByRole('status').filter({ hasText: 'Search results open.' })).toHaveClass(/rr-block/)
  await page.getByRole('combobox', { name: 'Progress state', exact: true }).selectOption('all')
  await input.fill('Soul')
  await expect(page.locator('.search-result[aria-current="true"]')).toHaveCount(0)
  await page.locator('.search-result').nth(1).click()
  await expect(page.getByRole('region', { name: 'Visible upgrade results', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.getItem('idle-slayer-ascension-map.profile.v1'))).toBeNull()
})


test('modified input shortcuts preserve native editing and composing text', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox')
  await input.fill('Soul')
  await input.evaluate((element) => (element as HTMLInputElement).setSelectionRange(2, 2))
  await input.press('Shift+ArrowDown')
  await expect(input).toBeFocused()
  expect(await input.evaluate((element) => ({ start: (element as HTMLInputElement).selectionStart, end: (element as HTMLInputElement).selectionEnd }))).toEqual({ start: 2, end: 4 })
  for (const key of ['Control+ArrowDown', 'Alt+ArrowUp', 'Meta+ArrowUp', 'Shift+Enter']) {
    await input.press(key)
    await expect(input).toBeFocused()
    await expect(page.getByRole('region', { name: 'Visible upgrade results', exact: true })).toBeVisible()
  }
  expect(await input.evaluate((element) => {
    const event = new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true, isComposing: true })
    element.dispatchEvent(event)
    return event.defaultPrevented
  })).toBe(false)
  await expect(input).toBeFocused()
  await input.press('ArrowDown')
  const first = page.locator('.search-result').first()
  await expect(first).toBeFocused()
  await first.press('Shift+ArrowDown')
  await expect(first).toBeFocused()
  expect(await page.evaluate(() => localStorage.getItem('idle-slayer-ascension-map.profile.v1'))).toBeNull()
})

test('deferred reopening cannot steal later Tab focus or override a newer candidate', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox')
  await input.fill('Soul')
  await input.press('Escape')
  await expect(page.getByRole('region', { name: 'Visible upgrade results', exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: 'Toggle search results', exact: true })).toHaveAttribute('aria-expanded', 'false')
  await page.clock.install()
  await page.clock.pauseAt(await page.evaluate(() => Date.now()) + 1000)
  await input.press('ArrowDown')
  await expect(page.locator('.search-result').first()).toBeVisible()
  await input.press('Tab')
  const close = page.getByRole('button', { name: 'Close search results', exact: true })
  await expect(close).toBeFocused()
  await page.clock.runFor(64)
  await expect(close).toBeFocused()

  await close.press('Escape')
  await expect(input).toBeFocused()
  await input.press('ArrowDown')
  await input.press('ArrowUp')
  await expect(page.locator('.search-result').last()).toBeFocused()
  await page.clock.runFor(64)
  await expect(page.locator('.search-result').last()).toBeFocused()

  await page.keyboard.press('Escape')
  await input.press('ArrowDown')
  await input.fill('PRIVATE UNMATCHED FIXTURE')
  await page.clock.runFor(64)
  await expect(input).toBeFocused()
  await expect(page.locator('.search-result')).toHaveCount(0)
  await expect(page.locator('[aria-current="true"].search-result')).toHaveCount(0)
  expect(await page.evaluate(() => localStorage.getItem('idle-slayer-ascension-map.profile.v1'))).toBeNull()
})


test('Escape in a populated native search field closes results without clearing or reopening the query', async ({ page }) => {
  await page.goto('./')
  const input = page.getByRole('searchbox')
  const region = page.getByRole('region', { name: 'Visible upgrade results', exact: true })
  const toggle = page.getByRole('button', { name: 'Toggle search results', exact: true })
  await input.fill('Soul')
  const count = await region.locator('.search-result').count()
  expect(count).toBeGreaterThan(2)
  await input.press('Escape')
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('Soul')
  await expect(region).toHaveCount(0)
  await expect(toggle).toHaveAttribute('aria-expanded', 'false')
  await expect(page.getByRole('status', { name: 'Search result state', exact: true })).toHaveText('Search results closed.')
  await input.press('ArrowUp')
  await expect(region.locator('.search-result')).toHaveCount(count)
  await expect(region.locator('.search-result').last()).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(region).toHaveCount(0)
  await input.fill('')
  await input.press('Escape')
  await expect(region).toHaveCount(0)
  await expect(input).toHaveValue('')
  expect(await page.evaluate(() => localStorage.getItem('idle-slayer-ascension-map.profile.v1'))).toBeNull()
})
